# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c14def7cb943b49df6d25d1ee0378b61"
application_url = "https://example.com"
embedded = true
name = "movika-cod-form"

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
